spring.application.name=notification
server.port=${SERVER_PORT:8082}

# Kafka Settings
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=notification-group-fresh-v1
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# SMTP Settings
spring.mail.host=smtp.hostinger.com
spring.mail.port=587
spring.mail.password=${MAIL_PASSWORD}
spring.mail.username=${MAIL_USERNAME}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true