spring.data.mongodb.uri=mongodb://localhost:27017/examintel
spring.data.mongodb.database=examintel

# JWT Secret
examintel.app.jwtSecret=ExamIntelSecretKey2026
examintel.app.jwtExpirationMs=86400000

# Server Port
server.port=8080
