pipeline {
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t authservice ./authservice/1.1/'
            }
        }
        stage('Run Container') {
            steps {
                sh 'docker stop authservice || true'
                sh 'docker rm authservice || true'
                sh 'docker run -d --name authservice -p 8081:8080 --network host authservice'
            }
        }
    }
}
